items:
- uid: System.Security.AccessControl.PrivilegeNotHeldException
  id: PrivilegeNotHeldException
  parent: System.Security.AccessControl
  children:
  - System.Security.AccessControl.PrivilegeNotHeldException.#ctor
  - System.Security.AccessControl.PrivilegeNotHeldException.#ctor(System.String)
  - System.Security.AccessControl.PrivilegeNotHeldException.#ctor(System.String,System.Exception)
  - System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeName
  name: PrivilegeNotHeldException
  fullName: System.Security.AccessControl.PrivilegeNotHeldException
  type: Class
  source:
    remote: &o0
      path: src/System.Security.AccessControl/src/System/Security/AccessControl/PrivilegeNotHeldException.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Security.AccessControl/src/System/Security/AccessControl/PrivilegeNotHeldException.cs
    startLine: 9
  assemblies:
  - System.Security.AccessControl
  namespace: System.Security.AccessControl
  summary: The exception that is thrown when a method in the <xref href="System.Security.AccessControl" data-throw-if-not-resolved="false"></xref> namespace attempts to enable a privilege that it does not have.
  syntax:
    content: 'public sealed class PrivilegeNotHeldException : UnauthorizedAccessException'
    content.vb: Public NotInheritable Class PrivilegeNotHeldException Inherits UnauthorizedAccessException
  inheritance:
  - System.Object
- uid: System.Security.AccessControl.PrivilegeNotHeldException.#ctor
  id: '#ctor'
  parent: System.Security.AccessControl.PrivilegeNotHeldException
  name: PrivilegeNotHeldException()
  fullName: System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeNotHeldException()
  type: Constructor
  source:
    remote: *o0
    path: src/System.Security.AccessControl/src/System/Security/AccessControl/PrivilegeNotHeldException.cs
    startLine: 13
  assemblies:
  - System.Security.AccessControl
  namespace: System.Security.AccessControl
  summary: Initializes a new instance of the <xref href="System.Security.AccessControl.PrivilegeNotHeldException" data-throw-if-not-resolved="false"></xref> class.
  syntax:
    content: public PrivilegeNotHeldException()
    content.vb: Public Sub New
- uid: System.Security.AccessControl.PrivilegeNotHeldException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Security.AccessControl.PrivilegeNotHeldException
  name: PrivilegeNotHeldException(String)
  fullName: System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeNotHeldException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/System.Security.AccessControl/src/System/Security/AccessControl/PrivilegeNotHeldException.cs
    startLine: 18
  assemblies:
  - System.Security.AccessControl
  namespace: System.Security.AccessControl
  summary: Initializes a new instance of the <xref href="System.Security.AccessControl.PrivilegeNotHeldException" data-throw-if-not-resolved="false"></xref> class by using the specified privilege.
  syntax:
    content: public PrivilegeNotHeldException(string privilege)
    content.vb: Public Sub New(privilege As String)
    parameters:
    - id: privilege
      type: System.String
      description: The privilege that is not enabled.
- uid: System.Security.AccessControl.PrivilegeNotHeldException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Security.AccessControl.PrivilegeNotHeldException
  name: PrivilegeNotHeldException(String, Exception)
  fullName: System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeNotHeldException(System.String, System.Exception)
  type: Constructor
  source:
    remote:
      path: src/System.Security.AccessControl/ref/System.Security.AccessControl.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Security.AccessControl/ref/System.Security.AccessControl.cs
    startLine: 442
  assemblies:
  - System.Security.AccessControl
  namespace: System.Security.AccessControl
  summary: Initializes a new instance of the <xref href="System.Security.AccessControl.PrivilegeNotHeldException" data-throw-if-not-resolved="false"></xref> class by using the specified exception.
  syntax:
    content: public PrivilegeNotHeldException(string privilege, Exception inner)
    content.vb: Public Sub New(privilege As String, inner As Exception)
    parameters:
    - id: privilege
      type: System.String
      description: The privilege that is not enabled.
    - id: inner
      type: System.Exception
      description: The exception that is the cause of the current exception. If the *innerException* parameter is not a null reference (Nothing in Visual Basic), the current exception is raised in a catch block that handles the inner exception.
- uid: System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeName
  id: PrivilegeName
  parent: System.Security.AccessControl.PrivilegeNotHeldException
  name: PrivilegeName
  fullName: System.Security.AccessControl.PrivilegeNotHeldException.PrivilegeName
  type: Property
  source:
    remote: *o0
    path: src/System.Security.AccessControl/src/System/Security/AccessControl/PrivilegeNotHeldException.cs
    startLine: 30
  assemblies:
  - System.Security.AccessControl
  namespace: System.Security.AccessControl
  summary: Gets the name of the privilege that is not enabled.
  syntax:
    content: public string PrivilegeName { get; }
    content.vb: Public ReadOnly Property PrivilegeName As String
    parameters: []
    return:
      type: System.String
      description: The name of the privilege that the method failed to enable.
references:
- uid: System.Security.AccessControl
  isExternal: false
  name: System.Security.AccessControl
  fullName: System.Security.AccessControl
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
