items:
- uid: System.Reflection.AmbiguousMatchException
  id: AmbiguousMatchException
  parent: System.Reflection
  children:
  - System.Reflection.AmbiguousMatchException.#ctor
  - System.Reflection.AmbiguousMatchException.#ctor(System.String)
  - System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)
  name: AmbiguousMatchException
  fullName: System.Reflection.AmbiguousMatchException
  type: Class
  source:
    remote: &o0
      path: src/mscorlib/src/System/Reflection/AmbiguousMatchException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Reflection/AmbiguousMatchException.cs
    startLine: 19
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: The exception that is thrown when binding to a member results in more than one member matching the binding criteria. This class cannot be inherited.
  syntax:
    content: 'public sealed class AmbiguousMatchException : Exception'
    content.vb: Public NotInheritable Class AmbiguousMatchException Inherits Exception
  inheritance:
  - System.Object
- uid: System.Reflection.AmbiguousMatchException.#ctor
  id: '#ctor'
  parent: System.Reflection.AmbiguousMatchException
  name: AmbiguousMatchException()
  fullName: System.Reflection.AmbiguousMatchException.AmbiguousMatchException()
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/Reflection/AmbiguousMatchException.cs
    startLine: 24
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.AmbiguousMatchException" data-throw-if-not-resolved="false"></xref> class with an empty message string and the root cause exception set to null.
  syntax:
    content: public AmbiguousMatchException()
    content.vb: Public Sub New
- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Reflection.AmbiguousMatchException
  name: AmbiguousMatchException(String)
  fullName: System.Reflection.AmbiguousMatchException.AmbiguousMatchException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/Reflection/AmbiguousMatchException.cs
    startLine: 29
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.AmbiguousMatchException" data-throw-if-not-resolved="false"></xref> class with its message string set to the given message and the root cause exception set to null.
  syntax:
    content: public AmbiguousMatchException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: A string indicating the reason this exception was thrown.
- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Reflection.AmbiguousMatchException
  name: AmbiguousMatchException(String, Exception)
  fullName: System.Reflection.AmbiguousMatchException.AmbiguousMatchException(System.String, System.Exception)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/Reflection/AmbiguousMatchException.cs
    startLine: 33
  assemblies:
  - System.Reflection
  namespace: System.Reflection
  summary: Initializes a new instance of the <xref href="System.Reflection.AmbiguousMatchException" data-throw-if-not-resolved="false"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public AmbiguousMatchException(string message, Exception inner)
    content.vb: Public Sub New(message As String, inner As Exception)
    parameters:
    - id: message
      type: System.String
      description: The error message that explains the reason for the exception.
    - id: inner
      type: System.Exception
      description: The exception that is the cause of the current exception. If the *inner* parameter is not null, the current exception is raised in a catch block that handles the inner exception.
references:
- uid: System.Reflection
  isExternal: false
  name: System.Reflection
  fullName: System.Reflection
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
